columnSuffix: null
handle: typesOfTherapyOfferred
instructions: null
name: 'Types of therapy you offer'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:49141ff0-5149-43b7-91d1-5c8d09a915ed'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
